# 2026 ZSH Config

# 1. Path & Environment
export PATH=$HOME/.local/bin:$PATH
export EDITOR="nvim"
export TERMINAL="wezterm"

# 2. History
HISTFILE="$HOME/.zsh_history"
HISTSIZE=10000
SAVEHIST=10000
setopt EXTENDED_HISTORY
setopt HIST_EXPIRE_DUPS_FIRST
setopt HIST_IGNORE_DUPS
setopt HIST_IGNORE_ALL_DUPS
setopt HIST_IGNORE_SPACE
setopt HIST_FIND_NO_DUPS
setopt HIST_SAVE_NO_DUPS

# 3. Completion System
autoload -Uz compinit
compinit
zstyle ':completion:*' matcher-list 'm:{a-z}={A-Za-z}'
zstyle ':completion:*' menu no
zstyle ':completion:*' list-colors "${(s.:.)LS_COLORS}"

# 4. Plugins
# We assume these are installed via Pacman/AUR (zsh-autosuggestions, etc.)
source /usr/share/zsh/plugins/zsh-syntax-highlighting/zsh-syntax-highlighting.zsh 2>/dev/null || true
source /usr/share/zsh/plugins/zsh-autosuggestions/zsh-autosuggestions.zsh 2>/dev/null || true
# FZF-Tab (Assuming installed to /usr/share/zsh/plugins/fzf-tab-git/fzf-tab.zsh or similar)
# We might need to adjust this path depending on the AUR package
source /usr/share/zsh/plugins/fzf-tab-git/fzf-tab.zsh 2>/dev/null || source /usr/share/fzf-tab/fzf-tab.zsh 2>/dev/null || true

# 5. Magician Integration (Dynamic Colors)
# This file is generated by Magician (via Gowall or directly)
MAGICAL_COLORS="$HOME/.cache/wal/colors.sh"
if [ -f "$MAGICAL_COLORS" ]; then
    source "$MAGICAL_COLORS"
    
    # Apply to FZF (using the variables from colors.sh)
    # Magician's colors.sh usually exports color0..color15
    export FZF_DEFAULT_OPTS="
      --color=bg+:$color1,bg:$color0,spinner:$color6,hl:$color1
      --color=fg:$color7,header:$color1,info:$color5,pointer:$color6
      --color=marker:$color6,fg+:$color7,prompt:$color5,hl+:$color1"
fi

# 6. FZF-Tab Previews (The "Wow" Factor)
# Preview directory contents with eza when tabbing cd
zstyle ':fzf-tab:complete:cd:*' fzf-preview 'eza -1 --color=always $realpath'
zstyle ':fzf-tab:complete:__zoxide_z:*' fzf-preview 'eza -1 --color=always $realpath'
# Preview file contents with bat
zstyle ':fzf-tab:complete:*:*' fzf-preview 'bat --color=always --style=numbers --line-range=:500 $realpath'

# 7. Aliases (The Workflow)
alias ls="eza --icons"
alias ll="eza -l --icons --group-directories-first"
alias la="eza -la --icons --group-directories-first"
alias cat="bat"
alias grep="rg"
alias find="fd"
alias c="clear"
alias y="yazi"
# DCLI shortcuts
alias sync="dcli sync"
alias conf="cd ~/.config/arch-config"

# 8. Initialization
export STARSHIP_CONFIG="$HOME/.config/starship/starship.toml"
eval "$(zoxide init zsh)"
eval "$(starship init zsh)"
