# Shell variables
# Generated by Lis-OS Magician

# Wallpaper
wallpaper="{{ wallpaper }}"

# Special
background='{{ colors.bg }}'
foreground='{{ colors.fg }}'
cursor='{{ colors.fg }}'

# Colors
color0='{{ colors.bg }}'
color1='{{ colors.sem_red }}'
color2='{{ colors.syn_acc }}'
color3='{{ colors.ui_sec }}'
color4='{{ colors.ui_prim }}'
color5='{{ colors.syn_acc }}'
color6='{{ colors.ui_sec }}'
color7='{{ colors.fg }}'
color8='{{ colors.ui_sec }}'
color9='{{ colors.sem_red }}'
color10='{{ colors.syn_acc }}'
color11='{{ colors.ui_sec }}'
color12='{{ colors.ui_prim }}'
color13='{{ colors.syn_acc }}'
color14='{{ colors.ui_sec }}'
color15='{{ colors.fg }}'

# FZF
export FZF_DEFAULT_OPTS="
    $FZF_DEFAULT_OPTS
    --color fg:{{ colors.fg }},bg:{{ colors.bg }},hl:{{ colors.ui_prim }}
    --color fg+:{{ colors.fg }},bg+:{{ colors.ui_sec }},hl+:{{ colors.ui_prim }}
    --color info:{{ colors.syn_acc }},prompt:{{ colors.ui_prim }},pointer:{{ colors.syn_acc }}
    --color marker:{{ colors.syn_acc }},spinner:{{ colors.syn_acc }},header:{{ colors.ui_prim }}
"
