import { Variable, GLib } from "astal";
import { monitorFile, readFileAsync } from "astal/file";

// This module provides a single, global, reactive variable
// containing the icon manifest generated by the backend.

const MANIFEST_PATH = `${GLib.get_home_dir()}/.cache/lis-icons/manifest.json`;
const SIGNAL_FILE = `${GLib.get_home_dir()}/.cache/theme-engine/signal`;

export interface IconManifest {
  primary: { [app_id: string]: string };
  accent: { [app_id: string]: string };
}

// 1. Create the reactive variable that will be the single source of truth.
const iconManifest = new Variable<IconManifest | null>(null);

// 2. Define the function that loads and updates the variable.
const loadManifest = () => {
  readFileAsync(MANIFEST_PATH)
    .then((contents) => {
      const parsed = JSON.parse(contents) as IconManifest;
      iconManifest.set(parsed);
      print("[IconService] Icon manifest loaded successfully.");
    })
    .catch((err) => {
      print(`[IconService] CRITICAL: Failed to load icon manifest: ${err}`);
      // On failure, set a default empty state to prevent crashes.
      iconManifest.set({ primary: {}, accent: {} });
    });
};

// 3. Set up the watcher to automatically reload on theme changes.
monitorFile(SIGNAL_FILE, () => {
  print("[IconService] Signal received. Reloading icon manifest...");
  loadManifest();
});

// 4. Perform the initial load when the application starts.
loadManifest();

// 5. Export the reactive variable itself for other components to use.
export default iconManifest;
