{
  config,
  pkgs,
  lib,
  inputs,
  host,
  astalPkgs,
  ...
}:

let
  variables = import ../../../../hosts/variables.nix;
  inherit (variables)
    browser
    terminal
    stylixImage
    startupApps
    monitorConfig
    ;

  barChoice = variables.barChoice or "waybar";

  # FIX: Use .niri instead of .default
  niriPkg = pkgs.niri;

  hostKeybindsPath = ./hosts/${host}/keybinds.nix;
  hostKeybinds =
    if builtins.pathExists hostKeybindsPath then import hostKeybindsPath { inherit host; } else "";

  keybindsModule = import ./keybinds.nix {
    inherit
      host
      terminal
      browser
      barChoice
      hostKeybinds
      config
      ;
  };
  windowrulesModule = import ./windowrules.nix { inherit host; };
  layoutModule = import ./layout.nix { inherit config; };
  workspacesModule = import ./workspaces.nix { };
  startupModule = import ./startup.nix {
    inherit
      host
      stylixImage
      startupApps
      barChoice
      pkgs
      ;
  };

  hostOutputsPath = ./hosts/${host}/outputs.nix;
  hostOutputs =
    if builtins.pathExists hostOutputsPath then
      import hostOutputsPath { inherit host; }
    else
      monitorConfig;

  hostWindowRulesPath = ./hosts/${host}/windowrules.nix;
  hostWindowRules =
    if builtins.pathExists hostWindowRulesPath then
      import hostWindowRulesPath { inherit host; }
    else
      "";

  baseConfig = ''
    // Niri Configuration for ${host}
    // Generated by NixOS configuration - BASE PART
    ${hostOutputs}
    ${workspacesModule}
    ${layoutModule}
    ${keybindsModule}
    ${windowrulesModule}
    ${hostWindowRules}
    ${startupModule}

    environment {
          XDG_CURRENT_DESKTOP "niri"
          MOZ_ENABLE_WAYLAND "1"
          NIXOS_OZONE_WL "1"
          ELECTRON_OZONE_PLATFORM_HINT "wayland"
          QT_QPA_PLATFORM "wayland"
          QT_QPA_PLATFORMTHEME "gtk3"
          QT_QPA_PLATFORMTHEME_QT6 "gtk3"
          TERMINAL "${terminal}"
          XCURSOR_THEME "Bibata-Modern-Ice"
          XCURSOR_SIZE "24"
          __GL_GSYNC_ALLOWED "1"
          __GL_VRR_ALLOWED "1"
          PROTON_ENABLE_NVAPI "1"
          PROTON_HIDE_NVIDIA_GPU "0"
          PROTON_ENABLE_NGX_UPDATER "1"
    }

    hotkey-overlay {
        skip-at-startup
    }

    prefer-no-csd

  '';
in
{
  home.packages = with pkgs; [
    niriPkg
    udiskie
    xwayland-satellite
    swww
    grim
    slurp
    wl-clipboard
    swappy
  ];

  xdg.configFile."niri/config-base.kdl".text = baseConfig;

  systemd.user.services.niri-config-assembler = {
    Unit = {
      Description = "Assemble Niri Config (Base + Colors)";
      Before = [ "graphical-session.target" ];
    };
    Service = {
      Type = "oneshot";
      ExecStart = pkgs.writeShellScript "assemble-niri-config" ''
                BASE="$HOME/.config/niri/config-base.kdl"
                COLORS="$HOME/.config/niri/colors.kdl"
                FINAL="$HOME/.config/niri/config.kdl"

                # 1. Ensure Colors file exists with valid syntax
                if [ ! -f "$COLORS" ]; then
                  mkdir -p "$(dirname "$COLORS")"
                  cat <<EOF > "$COLORS"
        window-rule {
            border {
                active-color "#FF0000"
                inactive-color "#00FF00"
                width 2
            }
        }
        EOF
                fi

                # 2. Assemble safely (Force newlines)
                cat "$BASE" > "$FINAL"
                echo "" >> "$FINAL"  # <--- CRITICAL SAFETY NEWLINE
                cat "$COLORS" >> "$FINAL"
      '';
    };
    Install.WantedBy = [ "graphical-session.target" ];
  };

  home.activation.setupNiriConfig = lib.hm.dag.entryAfter [ "writeBoundary" ] ''
    $DRY_RUN_CMD ${pkgs.systemd}/bin/systemctl --user start niri-config-assembler.service
  '';

  systemd.user.targets.niri-session = {
    Unit = {
      Description = "Niri compositor session";
      BindsTo = "graphical-session.target";
      Wants = "graphical-session-pre.target";
      After = "graphical-session-pre.target";
    };
  };

  systemd.user.services.waybar-niri = lib.mkIf (barChoice == "waybar") {
    Unit = {
      Description = "Waybar status bar";
      PartOf = "graphical-session.target";
      ConditionEnvironment = "XDG_CURRENT_DESKTOP=niri";
    };
    Service = {
      ExecStart = "${pkgs.waybar}/bin/waybar";
      Restart = "on-failure";
    };
    Install.WantedBy = [ "graphical-session.target" ];
  };

  systemd.user.services.xwayland-satellite = {
    Unit = {
      Description = "Xwayland outside Wayland";
      BindsTo = "graphical-session.target";
      After = "graphical-session.target";
    };
    Service = {
      Type = "notify";
      NotifyAccess = "all";
      ExecStart = "${pkgs.xwayland-satellite}/bin/xwayland-satellite";
      StandardOutput = "journal";
      Restart = "on-failure";
    };
    Install.WantedBy = [ "graphical-session.target" ];
  };
}
