// AUTO-GENERATED FILE - DO NOT EDIT
// Generated by scripts/gen-registry.js
// Definition of the "Bundle Reality" - All available widgets.

import Audio from '../widgets/Audio';
import DashboardButton from '../widgets/DashboardButton';
import DateTime from '../widgets/DateTime';
import MediaPro from '../widgets/MediaPro'; // V5 Compliant MediaPro
import ResourceUsage from '../widgets/ResourceUsage';
import Tray from '../widgets/Tray';

import Weather from '../widgets/Weather';
import WindowTitle from '../widgets/WindowTitle';
import Workspaces from '../widgets/Workspaces';

export const WIDGET_MAP = {
    "audio": Audio,
    "dashboardbutton": DashboardButton,
    "datetime": DateTime,
    "media": MediaPro,
    "resourceusage": ResourceUsage,
    "tray": Tray,

    "weather": Weather,
    "windowtitle": WindowTitle,
    "workspaces": Workspaces,
} as const;

export type WidgetId = keyof typeof WIDGET_MAP;

export default WIDGET_MAP;
